application: healthkick
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts
  

- url: .*
  script: main.py

- url: /_ah/mail/.+
  script: main.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico


